import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, Type } from "@google/genai";
import fs from "fs";
import path from "path";
import os from "os";

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    
    // We can accept PDFs or Word docs, but GenAI files handle PDFs extremely well natively
    if (file.type !== "application/pdf") return NextResponse.json({ error: "Only PDF files are allowed" }, { status: 400 });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) return NextResponse.json({ error: "GEMINI_API_KEY is not configured" }, { status: 500 });

    const ai = new GoogleGenAI({ apiKey });

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    const tempFileId = `gamify_${Date.now()}_${Math.random().toString(36).substring(7)}.pdf`;
    const tempFilePath = path.join(os.tmpdir(), tempFileId);
    fs.writeFileSync(tempFilePath, buffer);

    console.log(`[Gamify] Uploaded PDF size: ${buffer.length} bytes to temp storage.`);

    const uploadResult = await ai.files.upload({
      file: tempFilePath,
      config: { mimeType: "application/pdf" },
    });

    console.log(`[Gamify] Google File API connected. URI: ${uploadResult.uri}`);

    if (fs.existsSync(tempFilePath)) {
      fs.unlinkSync(tempFilePath);
    }

    if (uploadResult.name) {
      let fileState = uploadResult.state;
      let attempts = 0;
      while (fileState !== "ACTIVE" && attempts < 10) {
        await new Promise(resolve => setTimeout(resolve, 2000));
        const fileInfo = await ai.files.get({ name: uploadResult.name });
        fileState = fileInfo.state;
        attempts++;
        console.log(`[Gamify] File state: ${fileState} (attempt ${attempts})`);
      }
      if (fileState !== "ACTIVE") {
        throw new Error(`File processing timed out (state: ${fileState}). Try a smaller PDF.`);
      }
    }

    const response = await ai.models.generateContent({
      model: "gemini-flash-lite-latest",
      contents: [
        { text: `Analyze this document. It is an exam, assignment, or worksheet. Extract all the multiple-choice questions you can find from it directly. For each question, extract its exact options exactly as written. Determine the correct answer for each among those options. Do not create new questions; only extract existing ones. If the document has no explicit multiple choice questions, infer potential options based on the material, but prefer direct extraction.` },
        { fileData: { fileUri: uploadResult.uri, mimeType: uploadResult.mimeType } }
      ],
      config: {
        systemInstruction: "You are a precise grading assistant capable of extracting literal exam questions. You must pull the exact text of the question and its options, and authoritatively determine the correct answer.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          description: "List of extracted exam questions.",
          properties: {
            questions: {
              type: Type.ARRAY,
              description: `List of extracted multiple choice questions with options and answers.`,
              items: {
                type: Type.OBJECT,
                properties: {
                  question: { type: Type.STRING },
                  A: { type: Type.STRING, description: "Option A text" },
                  B: { type: Type.STRING, description: "Option B text" },
                  C: { type: Type.STRING, description: "Option C text" },
                  D: { type: Type.STRING, description: "Option D text" },
                  answer: { type: Type.STRING, description: "The exact text of the correct option (e.g., 'A. the text', or whatever the specific text of the valid option is)" },
                },
                required: ["question", "A", "B", "C", "D", "answer"]
              }
            }
          },
          required: ["questions"]
        }
      }
    });

    try {
      if (uploadResult.name) {
        await ai.files.delete({ name: uploadResult.name });
        console.log(`[Gamify] Deleted File ${uploadResult.name} from Google Servers.`);
      }
    } catch (err) {
      console.warn("Failed to delete File ID.");
    }

    const aiText = response.text;
    if (!aiText) throw new Error("No text generated by Gemini");

    const parsed = JSON.parse(aiText);

    return NextResponse.json({
      success: true,
      questions: parsed.questions
    });

  } catch (error: any) {
    console.error("[Gamify Upload] Encountered an error:", error);
    return NextResponse.json(
      { error: "Failed to process Gamify upload", details: error.message },
      { status: 500 }
    );
  }
}
