import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, Type } from "@google/genai";
import fs from "fs";
import path from "path";
import os from "os";

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    
    // We can accept PDFs or Word docs, but GenAI files handle PDFs extremely well natively
    if (file.type !== "application/pdf") return NextResponse.json({ error: "Only PDF files are allowed" }, { status: 400 });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) return NextResponse.json({ error: "GEMINI_API_KEY is not configured" }, { status: 500 });

    const ai = new GoogleGenAI({ apiKey });

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    const tempFileId = `gamify_${Date.now()}_${Math.random().toString(36).substring(7)}.pdf`;
    const tempFilePath = path.join(os.tmpdir(), tempFileId);
    fs.writeFileSync(tempFilePath, buffer);

    console.log(`[Gamify] Uploaded PDF size: ${buffer.length} bytes to temp storage.`);

    const uploadResult = await ai.files.upload({
      file: tempFilePath,
      config: { mimeType: "application/pdf" },
    });

    console.log(`[Gamify] Google File API connected. URI: ${uploadResult.uri}`);

    if (fs.existsSync(tempFilePath)) {
      fs.unlinkSync(tempFilePath);
    }

    if (uploadResult.name) {
      let fileState = uploadResult.state;
      let attempts = 0;
      while (fileState !== "ACTIVE" && attempts < 10) {
        await new Promise(resolve => setTimeout(resolve, 2000));
        const fileInfo = await ai.files.get({ name: uploadResult.name });
        fileState = fileInfo.state;
        attempts++;
        console.log(`[Gamify] File state: ${fileState} (attempt ${attempts})`);
      }
      if (fileState !== "ACTIVE") {
        throw new Error(`File processing timed out (state: ${fileState}). Try a smaller PDF.`);
      }
    }

    const response = await ai.models.generateContent({
      model: "gemini-flash-lite-latest",
      contents: [
        { text: `Analyze this document. It is an exam, assignment, or worksheet. Extract the exact questions from the document. For each question:
1. If the question already has multiple-choice options written in the document, extract them exactly as written.
2. If the question does NOT have multiple-choice options (e.g. free-response, fill-in-the-blank, true/false, short answer), CREATE four plausible multiple-choice options (A, B, C, D) based on the content, where one is the correct answer and the other three are reasonable distractors.
Determine the correct answer for each question. Do not invent new questions — only use questions that actually appear in the document.` },
        { fileData: { fileUri: uploadResult.uri, mimeType: uploadResult.mimeType } }
      ],
      config: {
        systemInstruction: "You are a precise grading assistant. Extract literal questions from the document. If a question has existing MCQ options, use them. If not, generate plausible A/B/C/D options. Always determine the correct answer authoritatively.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          description: "List of extracted exam questions.",
          properties: {
            questions: {
              type: Type.ARRAY,
              description: `List of extracted questions with options and answers.`,
              items: {
                type: Type.OBJECT,
                properties: {
                  question: { type: Type.STRING },
                  A: { type: Type.STRING, description: "Option A text" },
                  B: { type: Type.STRING, description: "Option B text" },
                  C: { type: Type.STRING, description: "Option C text" },
                  D: { type: Type.STRING, description: "Option D text" },
                  answer: { type: Type.STRING, description: "Correct letter A, B, C, or D" },
                },
                required: ["question", "A", "B", "C", "D", "answer"]
              }
            }
          },
          required: ["questions"]
        }
      }
    });

    // Clean up server-side file from Google AI Storage
    try {
      if (uploadResult.name) {
        await ai.files.delete({ name: uploadResult.name });
        console.log(`[Tome] Deleted Grimoire ${uploadResult.name} from Google Servers.`);
      }
    } catch (err) {
      console.warn("Failed to delete File ID. Let 48Hr TTL execute.");
    }

    const aiText = response.text;
    if (!aiText) throw new Error("No text generated by Gemini");

    const parsed = JSON.parse(aiText);

    return NextResponse.json({
      success: true,
      questions: parsed.questions
    });

  } catch (error: any) {
    console.error("[Tome] Failed to process scroll:", error);

    if (error.status === 429 || error.message?.includes("429") || error.message?.includes("quota")) {
      const match = error.message?.match(/(\d+)\s*sec/i) || error.message?.match(/Wait (\d+)/i);
      const delay = match ? parseInt(match[1], 10) : 60;

      return NextResponse.json(
        {
          error: `The Arcane energies are depleted. Please wait ${delay} seconds before attempting another trial.`,
          retryDelay: delay
        },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { error: "Failed to process the Trial of the Tome", details: error.message },
      { status: 500 }
    );
  }
}
