import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, Type } from "@google/genai";
import { doc, setDoc } from "firebase/firestore";
import fs from "fs";
import path from "path";
import os from "os";
import { db } from "../../../lib/firebase";

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    if (file.type !== "application/pdf") return NextResponse.json({ error: "Only PDF files are allowed" }, { status: 400 });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) return NextResponse.json({ error: "GEMINI_API_KEY is not configured" }, { status: 500 });

    const ai = new GoogleGenAI({ apiKey });

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Save PDF to a temporary file using os.tmpdir() to prevent Vercel ENOENT errors
    const tempFileId = `sacrifice_${Date.now()}_${Math.random().toString(36).substring(7)}.pdf`;
    const tempFilePath = path.join(os.tmpdir(), tempFileId);
    fs.writeFileSync(tempFilePath, buffer);

    console.log(`[Archivist] Uploaded PDF size: ${buffer.length} bytes. Saved temp file to: ${tempFilePath}`);

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        { text: "Analyze this document. Identify the overarching Subject (e.g. Biology, Math, History, Physics). Then, identify the top 5 distinct Core Concepts. Generate exactly 1 Multiple Choice Question for each concept (total exactly 5 MCQs)." },
        { inlineData: { data: buffer.toString("base64"), mimeType: "application/pdf" } }
      ],
      config: {
        systemInstruction: "You are an Archivist wizard capable of reading any discipline. Classify the discipline and extract pure, conceptual MCQs.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          description: "Subject classification and extracted spell cards.",
          properties: {
            subject: { type: Type.STRING, description: "The overarching academic subject of the document, e.g. Biology, Mathematics, World History, Computing." },
            spells: {
              type: Type.ARRAY,
              description: "List of exactly 5 multiple choice questions mapped to the top 5 distinct concepts.",
              items: {
                type: Type.OBJECT,
                properties: {
                  question: { type: Type.STRING },
                  A: { type: Type.STRING },
                  B: { type: Type.STRING },
                  C: { type: Type.STRING },
                  D: { type: Type.STRING },
                  answer: { type: Type.STRING, description: "Correct letter A, B, C, or D" },
                  difficulty: { type: Type.INTEGER, description: "Assign a difficulty scale from 1 (easy baseline) to 5 (extremely complex nuance)." }
                },
                required: ["question", "A", "B", "C", "D", "answer", "difficulty"]
              }
            }
          },
          required: ["subject", "spells"]
        }
      }
    });

    // Clean up local temp file as requested so the tent stays clean!
    if (fs.existsSync(tempFilePath)) {
      fs.unlinkSync(tempFilePath);
      console.log(`[Archivist] Successfully deleted temp file from /tmp: ${tempFilePath}`);
    }

    const aiText = response.text;
    if (!aiText) throw new Error("No text generated by Gemini");
    
    const extraction = JSON.parse(aiText);
    const { subject, spells } = extraction;
    
    console.log(`[Archivist] Discovered Domain: ${subject}. Forged ${spells.length} Spell Cards successfully.`);

    // Use os.tmpdir() for state writing to avoid ENOENT errors when Vercel attempts to write outside the root
    try {
      const swarmStatePath = path.join(os.tmpdir(), "state.json");
      let swarmState: any = {};
      if (fs.existsSync(swarmStatePath)) {
         swarmState = JSON.parse(fs.readFileSync(swarmStatePath, 'utf-8'));
      }
      
      swarmState.status = "battle_active";
      swarmState.subject = subject;
      swarmState.spells = spells;
      
      fs.writeFileSync(swarmStatePath, JSON.stringify(swarmState, null, 2), 'utf-8');
    } catch (e) {
      console.warn("Could not write local state.json to /tmp, failing over cleanly as Arbiter Firestore handles true state synced storage.");
    }
    
    // Update Firestore to sync Arbiter
    const battleDoc = doc(db, "gameData", "boss");
    await setDoc(battleDoc, {
        status: "battle_active",
        subject: subject,
        spells: spells,
        timestamp: Date.now()
    }, { merge: true });

    return NextResponse.json({
      success: true,
      message: `The Sacrifice was accepted into the Realm of ${subject}! The Battle has begun!`,
      spellsCount: spells.length,
      subject: subject,
      spells: spells
    });
  } catch (error: any) {
    console.error("[Archivist] Failed to process scroll:", error);
    return NextResponse.json(
      { error: "Failed to process the sacrifice", details: error.message },
      { status: 500 }
    );
  }
}
